name: streaks
description: "A new Flutter project."

publish_to: "none"

version: 1.0.7+11

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  equatable: ^2.0.3
  cupertino_icons: ^1.0.8
  path: ^1.6.4
  sqflite: ^2.3.2
  google_fonts: ^6.2.1
  lucide_icons: ^0.257.0
  gap: ^3.0.1
  flutter_color_models: ^1.3.3+2
  flex_color_scheme: ^8.0.2
  isar_flutter_libs: ^3.1.0+1
  isar: ^3.1.0+1
  path_provider: ^2.1.5
  timezone: ^0.10.0
  url_launcher: ^6.3.1
  home_widget: ^0.7.0
  flutter_heatmap_calendar: ^1.0.5
  purchases_flutter: ^8.7.5
  fluttertoast: ^8.2.12
  shared_preferences: ^2.5.3
  screenshot: ^3.0.0
  share_plus: ^11.1.0
  permission_handler: ^12.0.1
  gallery_saver_plus: ^3.2.8
  flutter_local_notifications: ^19.4.0
  flutter_native_splash: ^2.4.6
  flutter_timezone: ^4.1.1
  package_info_plus: ^8.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.5
  isar_generator: ^3.0.0

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  color: "#000000"
  background_image: "assets/app_icon.png"
  android_12:
    color: "#000000"
    icon_background_color: "#000000"
    image: "assets/app_icon.png"
    icon_background_color_dark: "#000000"
     