name: streaks
description: "A new Flutter project."

publish_to: "none"

version: 1.0.15+22

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  equatable: ^2.0.3
  cupertino_icons: ^1.0.8
  path: ^1.6.4
  sqflite: ^2.3.2
  google_fonts: ^6.2.1
  lucide_icons: ^0.257.0
  gap: ^3.0.1
  flutter_color_models: ^1.3.3+2
  flex_color_scheme: ^8.0.2
  isar_community_flutter_libs: ^3.3.0-dev.3
  isar_community: ^3.1.0+1
  path_provider: ^2.1.5
  timezone: ^0.10.0
  url_launcher: ^6.3.1
  home_widget: ^0.8.1
  flutter_heatmap_calendar: ^1.0.5
  purchases_flutter: ^9.9.5
  fluttertoast: ^9.0.0
  shared_preferences: ^2.5.3
  screenshot: ^3.0.0
  share_plus: ^12.0.1
  permission_handler: ^12.0.1
  gallery_saver_plus: ^3.2.8
  flutter_local_notifications: ^19.4.0
  flutter_native_splash: ^2.4.6
  flutter_timezone: ^5.0.1
  package_info_plus: ^9.0.0
  in_app_review: ^2.0.11
  confetti: ^0.8.0
  fl_chart: 1.0.0
  file_picker: ^10.3.3
  cloud_firestore: ^6.1.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  sign_in_with_apple: ^7.0.1
  google_sign_in: ^7.2.0
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.5
  isar_community_generator: ^3.0.0

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/badges/

flutter_native_splash:
  color: "#000000"
  background_image: "assets/app_icon.png"
  android_12:
    color: "#000000"
    icon_background_color: "#000000"
    image: "assets/app_icon.png"
    icon_background_color_dark: "#000000"
     